

<?php

class CheckEmbed extends ParseHtml{

}
/***
 * Variety way to have embeded file
 * 1. <embed> with fallback <noembed>
 * 2. <bgsound> not widely used as it is only supported in IE
 * 2. <object> introduces in html 4 with fallback any text between open and it's close tag.
 *
 *     Embed Flash Player content in a manner that exposes accessibility
Ensure applets provide valid text equivalents
Ensure audio that plays automatically can be controlled within the containing page
Ensure embedded and linked non-HTML media provide a link to an accessible plug-in
Ensure embedded elements and canvas elements provide a meaningful text equivalent
Ensure embedded objects are device-independent
Ensure embedded objects are directly accessible
Ensure the keyboard can be used to navigate through or past the embedded content
Ensure video, multimedia or animations that play automatically can be controlled within the containing page
Provide a text transcript for audio only presentations
Provide text equivalents for object elements
Provide text transcript or audio track of video only presentations
 */
?>
